import Shell from '@/components/Layout/Shell';
import { useTitle } from '@/utils/metas';
import { MantineProvider } from '@mantine/core';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  const title = useTitle();

  return (
    <>
      <Head>
        <title>{title ? `${title} | ` : '' || 'NextMantineExample'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MantineProvider withGlobalStyles withNormalizeCSS>
        <Shell>
          <Component {...pageProps} />
        </Shell>
      </MantineProvider>
    </>
  );
}
